# Generated by Django 2.2 on 2021-03-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=1000)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
