# Generated by Django 3.0 on 2021-03-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='edo',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
